services:
  chat:
    container_name: chat
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./backend/upload:/app/backend/upload
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - HASH_ALGORITHM=${HASH_ALGORITHM}
      - EXPIRATION_MINUTES=${EXPIRATION_MINUTES}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_URL=db
    depends_on:
      - db
  db:
    container_name: postgres
    image: postgres:17
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: /data/postgres
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - db:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  db:
