"""increased message size

Revision ID: b9ee5a220686
Revises: 72ba08c9a9ba
Create Date: 2025-09-14 20:45:42.116056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b9ee5a220686'
down_revision: Union[str, Sequence[str], None] = '72ba08c9a9ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'content',
               existing_type=sa.VARCHAR(length=1000),
               type_=sqlmodel.sql.sqltypes.AutoString(length=1024),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'content',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=1024),
               type_=sa.VARCHAR(length=1000),
               existing_nullable=False)
    # ### end Alembic commands ###
