name: Publish Docker containers

on:
  push:
    tags:
      - "v*.*.*"

env:
  REGISTRY: ghcr.io

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}


      - name: Build Container
        run: docker build -t ${{ env.REGISTRY }}/rykktiadloans/chat:${{ github.ref_name }} .

      - name: Push Container
        run: docker push ${{ env.REGISTRY }}/rykktiadloans/chat:${{ github.ref_name }}
